"""Generate backend/clipsieve/models.py from packages/schema/schemas/*.json.

Run from the repo root via `bun run schema`, or directly:
    cd backend && uv run python ../packages/schema/generate.py
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from merge import merge  # noqa: E402

HERE = Path(__file__).parent
BUILD = HERE / ".build"
MERGED = BUILD / "clipsieve.merged.json"
OUTPUT = HERE.parent.parent / "backend" / "clipsieve" / "models.py"
BANNER = "# GENERATED by packages/schema; do not edit\n"


def main() -> int:
    BUILD.mkdir(exist_ok=True)
    MERGED.write_text(json.dumps(merge(), indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    cmd = [
        "datamodel-codegen",
        "--input", str(MERGED),
        "--input-file-type", "jsonschema",
        "--output", str(OUTPUT),
        "--output-model-type", "pydantic_v2.BaseModel",
        "--target-python-version", "3.12",
        "--use-standard-collections",
        "--use-union-operator",
        "--field-constraints",
        # Annotated keeps constrained map values plain (dict[str, int], not dict[str, RootModel]).
        "--use-annotated",
        # Unions such as Question become `type X = A | B`, not RootModel, so isinstance() works.
        "--use-type-alias",
        "--snake-case-field",
        "--disable-timestamp",
        "--use-schema-description",
        "--use-double-quotes",
        "--extra-fields", "forbid",
        "--enum-field-as-literal", "none",
        "--use-subclass-enum",
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        print(result.stdout)
        print(result.stderr, file=sys.stderr)
        return result.returncode
    body = OUTPUT.read_text(encoding="utf-8")
    # Drop the generator's own header (filename + blank) so the banner is first and stable.
    lines = body.splitlines(keepends=True)
    while lines and lines[0].startswith("#"):
        lines.pop(0)
    while lines and lines[0].strip() == "":
        lines.pop(0)
    OUTPUT.write_text(BANNER + "".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(HERE.parent.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
