// Generate frontend/src/lib/types.ts from packages/schema/schemas/*.json.
// Run via `bun run --filter @clipsieve/schema generate`.
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile, type JSONSchema } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const schemasDir = join(here, "schemas");
const output = join(here, "..", "..", "frontend", "src", "lib", "types.ts");

type Json = Record<string, unknown>;

const refFileDef = /^(?<file>[a-z_]+\.json)?#\/\$defs\/(?<name>[A-Za-z0-9_]+)$/;
const refFileRoot = /^(?<file>[a-z_]+\.json)$/;

function rewriteRefs(
  node: unknown,
  titleByFile: Record<string, string>
): unknown {
  if (Array.isArray(node)) {
    return node.map((v) => rewriteRefs(v, titleByFile));
  }
  if (node && typeof node === "object") {
    const out: Json = {};
    for (const [key, value] of Object.entries(node as Json)) {
      if (key === "$ref" && typeof value === "string") {
        const def = value.match(refFileDef);
        if (def?.groups) {
          out[key] = `#/$defs/${def.groups.name}`;
          continue;
        }
        const root = value.match(refFileRoot);
        if (root?.groups) {
          out[key] = `#/$defs/${titleByFile[root.groups.file]}`;
          continue;
        }
        throw new Error(`unsupported $ref: ${value}`);
      }
      out[key] = rewriteRefs(value, titleByFile);
    }
    return out;
  }
  return node;
}

function snake(name: string): string {
  return name.replace(/(?<!^)(?=[A-Z])/g, "_").toLowerCase();
}

function merge(): JSONSchema {
  const files = readdirSync(schemasDir)
    .filter((f) => f.endsWith(".json"))
    .sort();
  const raw: Record<string, Json> = {};
  for (const f of files) {
    raw[f] = JSON.parse(readFileSync(join(schemasDir, f), "utf-8")) as Json;
  }
  const titleByFile: Record<string, string> = {};
  for (const [name, doc] of Object.entries(raw)) {
    titleByFile[name] = doc.title as string;
  }
  const defs: Json = {};
  const rootProps: Json = {};
  for (const [name, doc] of Object.entries(raw)) {
    for (const [defName, defSchema] of Object.entries(
      (doc.$defs as Json | undefined) ?? {}
    )) {
      if (defName in defs) {
        throw new Error(`duplicate $def ${defName} in ${name}`);
      }
      defs[defName] = defSchema;
    }
    if (name === "common.json") {
      continue;
    }
    const top: Json = {};
    for (const [k, v] of Object.entries(doc)) {
      if (k !== "$schema" && k !== "$id" && k !== "$defs") {
        top[k] = v;
      }
    }
    defs[doc.title as string] = top;
    rootProps[snake(doc.title as string)] = { $ref: `#/$defs/${doc.title}` };
  }
  const merged = {
    $defs: defs,
    $id: "https://clipsieve.dev/schema/clipsieve.json",
    $schema: "https://json-schema.org/draft/2020-12/schema",
    additionalProperties: false,
    properties: rootProps,
    title: "ClipsieveSchemas",
    type: "object",
  };
  return rewriteRefs(merged, titleByFile) as JSONSchema;
}

const ts = await compile(merge(), "ClipsieveSchemas", {
  additionalProperties: false,
  bannerComment: "// GENERATED by packages/schema; do not edit",
  cwd: schemasDir,
  // Bounded arrays stay plain arrays (not tuple unions); Pydantic enforces lengths.
  ignoreMinAndMaxItems: true,
  strictIndexSignatures: false,
  style: { semi: true, singleQuote: false },
});
mkdirSync(dirname(output), { recursive: true });
writeFileSync(output, ts, "utf-8");
console.log(`wrote ${output}`);
