# GENERATED by packages/schema; do not edit
from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType


class Platform(StrEnum):
    youtube = "youtube"
    xiaohongshu = "xiaohongshu"
    local = "local"


class Stage(StrEnum):
    planning = "planning"
    collecting = "collecting"
    pass_one = "pass_one"
    extracting = "extracting"
    pass_two = "pass_two"
    selecting = "selecting"
    explaining = "explaining"
    done = "done"
    failed = "failed"


class RunEventType(StrEnum):
    run_created = "run_created"
    plan_ready = "plan_ready"
    plan_approved = "plan_approved"
    post_collected = "post_collected"
    pass_one_judged = "pass_one_judged"
    evidence_ready = "evidence_ready"
    judged = "judged"
    selected = "selected"
    explained = "explained"
    error = "error"
    stage_changed = "stage_changed"
    done = "done"


class Brief(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: str
    topic: str
    audience: str
    persona: str
    language_hint: str | None = None


class Query(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: str
    query: str
    lang: str


class Counters(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    collected: Annotated[int, Field(ge=0)]
    pass_one_kept: Annotated[int, Field(ge=0)]
    judged: Annotated[int, Field(ge=0)]
    shortlisted: Annotated[int, Field(ge=0)]
    review: Annotated[int, Field(ge=0)]
    errors: Annotated[int, Field(ge=0)]
    jev_input_tokens: Annotated[int, Field(ge=0)]
    jev_cost_usd: Annotated[float, Field(ge=0.0)]
    elapsed_s: Annotated[float, Field(ge=0.0)]


class TranscriptSegment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start_s: float
    end_s: float
    text: str


class Source(StrEnum):
    keyframe = "keyframe"
    image = "image"


class OcrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: Source
    index: int
    text: str


class CommentSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    count: Annotated[int, Field(ge=0)]
    top_terms: list[str]
    sample: list[str]


class Evidence(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    post_id: str
    transcript: list[TranscriptSegment]
    transcript_lang: str | None = None
    ocr: list[OcrItem]
    keyframes: Annotated[list[str], Field(max_length=8)]
    comment_summary: CommentSummary
    token_estimate: Annotated[int, Field(ge=0)]
    truncated: bool


class Type(StrEnum):
    choice = "choice"
    score = "score"
    noul = "noul"


class JudgeAnswer(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type
    value: Annotated[
        str | float,
        Field(
            description="label for choice, fractional score for score, probability for noul"
        ),
    ]
    probabilities: dict[str, float] | None = None
    confidence: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    legend: dict[str, str] | None = None


class PassName(StrEnum):
    pass_one = "pass_one"
    pass_two = "pass_two"


class JudgeResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    post_id: str
    pass_name: PassName
    model: str
    input_tokens: Annotated[int, Field(ge=0)]
    latency_ms: Annotated[int, Field(ge=0)]
    answers: dict[str, JudgeAnswer]


QuantitiesAdditionalProperty = TypeAliasType(
    "QuantitiesAdditionalProperty", Annotated[int, Field(ge=1)]
)


class Plan(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    run_id: str
    brief: Brief
    queries: list[Query]
    quantities: dict[str, QuantitiesAdditionalProperty]
    rubric_pack: str
    persona_fit_criteria: Annotated[list[str], Field(max_length=5, min_length=5)]
    approved_at: AwareDatetime | None = None


class PostText(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str | None = None
    caption: str | None = None
    hashtags: list[str]


class Type1(StrEnum):
    video = "video"
    image = "image"


class Media(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type1
    local_path: str | None = None
    duration_s: float | None = None
    index: int | None = None
    width: int | None = None
    height: int | None = None


class Metrics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    views: int | None = None
    likes: int | None = None
    comments: int | None = None
    shares: int | None = None
    saves: int | None = None


class Comment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: str
    likes: int | None = None


class Kind(StrEnum):
    video = "video"
    image_note = "image_note"


class Post(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(description="<platform>:<platform_id>")]
    platform: Platform
    url: str
    creator_hash: Annotated[
        str, Field(description="sha256 hex of salt:platform_creator_id")
    ]
    creator_display: str | None = None
    posted_at: AwareDatetime | None = None
    kind: Kind
    text: PostText
    media: list[Media]
    metrics: Metrics
    comments: Annotated[list[Comment], Field(max_length=50)]
    lang: Annotated[str | None, Field(description="BCP-47")] = None
    raw_ref: Annotated[str, Field(description="Path relative to the run root")]
    collected_at: AwareDatetime


class Pattern(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    observation: str
    hypothesis: str
    post_ids: list[str]


class ClipExplanation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    post_id: str
    why_it_works: str
    hook_quote: str
    weaknesses: str


class Gap(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    rationale: str
    post_ids: list[str]


class Concept(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    hook: str
    structure: str
    visual: str
    proof: str
    cta: str
    inspired_by_post_ids: list[str]


class Report(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    run_id: str
    patterns: list[Pattern]
    clips: list[ClipExplanation]
    gaps: list[Gap]
    concepts: list[Concept]
    caveats: list[str]


class ChoiceQuestion(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["choice"]
    instructions: str
    criteria: Annotated[dict[str, str], Field(max_length=255, min_length=2)]


class ScoreQuestion(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["score"]
    instructions: str
    criteria: Annotated[list[str], Field(max_length=10, min_length=2)]


class NoulQuestion(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["noul"]
    instructions: str


class HardFilters(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    risky_claim_max: Annotated[float | None, Field(ge=0.0, le=1.0)] = None


class Diversity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_share: Annotated[float, Field(ge=0.0, le=1.0)]


class SelectionPolicy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    weights: dict[str, float]
    hard_filters: HardFilters
    review_confidence_below: Annotated[float, Field(ge=0.0, le=1.0)]
    shortlist_size: Annotated[int, Field(ge=1)]
    diversity: dict[str, Diversity]


class LanguageMode(StrEnum):
    raw = "raw"
    translate_ = "translate"
    bilingual = "bilingual"


class RubricPack(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    version: Annotated[int, Field(ge=1)]
    jev_model: str
    language_mode: LanguageMode
    metadata_pass: list[str]
    pass_one_keep: Annotated[float, Field(ge=0.0, le=1.0)]
    questions: dict[str, ChoiceQuestion | ScoreQuestion | NoulQuestion]
    selection: SelectionPolicy


class Run(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    created_at: AwareDatetime
    stage: Stage
    brief: Brief
    platforms: list[str]
    quantities: dict[str, QuantitiesAdditionalProperty]
    rubric_pack: str
    counters: Counters
    paused: bool
    error: str | None = None


class RunEvent(BaseModel):
    """
    One line of events.jsonl. Payload shape depends on type; see the overview plan table. Validated by clipsieve.events.writer.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    run_id: str
    seq: Annotated[int, Field(ge=1)]
    ts: AwareDatetime
    type: RunEventType
    stage: Stage
    payload: dict[str, Any]


class ClipsieveSchemas(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    evidence: Evidence | None = None
    judge_result: JudgeResult | None = None
    plan: Plan | None = None
    post: Post | None = None
    report: Report | None = None
    rubric_pack: RubricPack | None = None
    run: Run | None = None
    run_event: RunEvent | None = None
