from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "packages" / "schema"))

from merge import merge  # noqa: E402

SCHEMA_FILES = [
    "common.json",
    "post.json",
    "evidence.json",
    "run_event.json",
    "rubric_pack.json",
    "plan.json",
    "report.json",
    "judge_result.json",
    "run.json",
]


def test_every_schema_file_present_and_titled():
    for name in SCHEMA_FILES:
        doc = json.loads((ROOT / "packages/schema/schemas" / name).read_text(encoding="utf-8"))
        assert doc["title"], name
        assert doc["$id"] == f"https://clipsieve.dev/schema/{name}"


def test_merge_flattens_refs_and_has_no_file_refs():
    merged = merge()
    text = json.dumps(merged)
    assert ".json#/" not in text
    for name in [
        "Post",
        "Evidence",
        "RunEvent",
        "RubricPack",
        "Plan",
        "Report",
        "JudgeResult",
        "Run",
        "Brief",
        "Counters",
        "Stage",
    ]:
        assert name in merged["$defs"], name


def test_generated_models_have_banner_and_classes():
    models = (ROOT / "backend/clipsieve/models.py").read_text(encoding="utf-8")
    assert models.startswith("# GENERATED by packages/schema; do not edit\n")
    for cls in [
        "class Post(",
        "class Evidence(",
        "class RunEvent(",
        "class RubricPack(",
        "class Plan(",
        "class Report(",
        "class JudgeResult(",
        "class Run(",
        "class Counters(",
        "class Brief(",
    ]:
        assert cls in models, cls


def test_generated_ts_has_banner_and_types():
    ts = (ROOT / "frontend/src/lib/types.ts").read_text(encoding="utf-8")
    assert ts.startswith("// GENERATED by packages/schema; do not edit")
    for name in [
        "Post",
        "Evidence",
        "RunEvent",
        "RubricPack",
        "Plan",
        "Report",
        "JudgeResult",
        "Run",
        "Counters",
        "Brief",
    ]:
        assert f"interface {name} " in ts or f"type {name} " in ts, name


@pytest.mark.parametrize("n", [1, 2, 3, 4, 5])
def test_fixture_posts_validate_and_keep_cjk(fixtures_dir: Path, n: int):
    from clipsieve.models import Post

    raw = (fixtures_dir / "posts" / f"local__fx-00{n}.json").read_text(encoding="utf-8")
    post = Post.model_validate_json(raw)
    assert post.id == f"local:fx-00{n}"
    assert (fixtures_dir / post.raw_ref).exists()
    assert len(post.comments) <= 50
    dumped = json.loads(post.model_dump_json())
    assert dumped["text"]["title"] == json.loads(raw)["text"]["title"]


def test_cjk_fixture_roundtrip_is_bytewise(fixtures_dir: Path):
    from clipsieve.models import Post

    post = Post.model_validate_json(
        (fixtures_dir / "posts/local__fx-003.json").read_text(encoding="utf-8")
    )
    assert post.text.title == "上海超市物价大公开 🇸🇬→🇨🇳"
    assert post.comments[0].text == "第4张真的绝了"
    assert post.kind.value == "image_note"
    assert len(post.media) == 4
