// GENERATED by packages/schema; do not edit

export type Platform = "youtube" | "xiaohongshu" | "local";
export type Question = ChoiceQuestion | ScoreQuestion | NoulQuestion;
export type Stage =
  "planning" | "collecting" | "pass_one" | "extracting" | "pass_two" | "selecting" | "explaining" | "done" | "failed";
export type RunEventType =
  | "run_created"
  | "plan_ready"
  | "plan_approved"
  | "post_collected"
  | "pass_one_judged"
  | "evidence_ready"
  | "judged"
  | "selected"
  | "explained"
  | "error"
  | "stage_changed"
  | "done";

export interface ClipsieveSchemas {
  evidence?: Evidence;
  judge_result?: JudgeResult;
  plan?: Plan;
  post?: Post;
  report?: Report;
  rubric_pack?: RubricPack;
  run?: Run;
  run_event?: RunEvent;
}
export interface Evidence {
  post_id: string;
  transcript: TranscriptSegment[];
  transcript_lang?: string;
  ocr: OcrItem[];
  /**
   * @maxItems 8
   */
  keyframes: string[];
  comment_summary: CommentSummary;
  token_estimate: number;
  truncated: boolean;
}
export interface TranscriptSegment {
  start_s: number;
  end_s: number;
  text: string;
}
export interface OcrItem {
  source: "keyframe" | "image";
  index: number;
  text: string;
}
export interface CommentSummary {
  count: number;
  top_terms: string[];
  sample: string[];
}
export interface JudgeResult {
  post_id: string;
  pass_name: "pass_one" | "pass_two";
  model: string;
  input_tokens: number;
  latency_ms: number;
  answers: {
    [k: string]: JudgeAnswer;
  };
}
export interface JudgeAnswer {
  type: "choice" | "score" | "noul";
  /**
   * label for choice, fractional score for score, probability for noul
   */
  value: string | number;
  probabilities?: {
    [k: string]: number;
  };
  confidence?: number;
  legend?: {
    [k: string]: string;
  };
}
export interface Plan {
  run_id: string;
  brief: Brief;
  queries: Query[];
  quantities: {
    [k: string]: number;
  };
  rubric_pack: string;
  /**
   * @minItems 5
   * @maxItems 5
   */
  persona_fit_criteria: string[];
  approved_at?: string;
}
export interface Brief {
  text: string;
  topic: string;
  audience: string;
  persona: string;
  language_hint?: string;
}
export interface Query {
  platform: string;
  query: string;
  lang: string;
}
export interface Post {
  /**
   * <platform>:<platform_id>
   */
  id: string;
  platform: Platform;
  url: string;
  /**
   * sha256 hex of salt:platform_creator_id
   */
  creator_hash: string;
  creator_display?: string;
  posted_at?: string;
  kind: "video" | "image_note";
  text: PostText;
  media: Media[];
  metrics: Metrics;
  /**
   * @maxItems 50
   */
  comments: Comment[];
  /**
   * BCP-47
   */
  lang?: string;
  /**
   * Path relative to the run root
   */
  raw_ref: string;
  collected_at: string;
}
export interface PostText {
  title?: string;
  caption?: string;
  hashtags: string[];
}
export interface Media {
  type: "video" | "image";
  local_path?: string;
  duration_s?: number;
  index?: number;
  width?: number;
  height?: number;
}
export interface Metrics {
  views?: number;
  likes?: number;
  comments?: number;
  shares?: number;
  saves?: number;
}
export interface Comment {
  text: string;
  likes?: number;
}
export interface Report {
  run_id: string;
  patterns: Pattern[];
  clips: ClipExplanation[];
  gaps: Gap[];
  concepts: Concept[];
  caveats: string[];
}
export interface Pattern {
  title: string;
  observation: string;
  hypothesis: string;
  post_ids: string[];
}
export interface ClipExplanation {
  post_id: string;
  why_it_works: string;
  hook_quote: string;
  weaknesses: string;
}
export interface Gap {
  title: string;
  rationale: string;
  post_ids: string[];
}
export interface Concept {
  hook: string;
  structure: string;
  visual: string;
  proof: string;
  cta: string;
  inspired_by_post_ids: string[];
}
export interface RubricPack {
  name: string;
  version: number;
  jev_model: string;
  language_mode: "raw" | "translate" | "bilingual";
  metadata_pass: string[];
  pass_one_keep: number;
  questions: {
    [k: string]: Question;
  };
  selection: SelectionPolicy;
}
export interface ChoiceQuestion {
  type: "choice";
  instructions: string;
  criteria: {
    [k: string]: string;
  };
}
export interface ScoreQuestion {
  type: "score";
  instructions: string;
  /**
   * @minItems 2
   * @maxItems 10
   */
  criteria: string[];
}
export interface NoulQuestion {
  type: "noul";
  instructions: string;
}
export interface SelectionPolicy {
  weights: {
    [k: string]: number;
  };
  hard_filters: {
    risky_claim_max?: number;
  };
  review_confidence_below: number;
  shortlist_size: number;
  diversity: {
    [k: string]: {
      max_share: number;
    };
  };
}
export interface Run {
  id: string;
  created_at: string;
  stage: Stage;
  brief: Brief;
  platforms: string[];
  quantities: {
    [k: string]: number;
  };
  rubric_pack: string;
  counters: Counters;
  paused: boolean;
  error?: string;
}
export interface Counters {
  collected: number;
  pass_one_kept: number;
  judged: number;
  shortlisted: number;
  review: number;
  errors: number;
  jev_input_tokens: number;
  jev_cost_usd: number;
  elapsed_s: number;
}
/**
 * One line of events.jsonl. Payload shape depends on type; see the overview plan table. Validated by clipsieve.events.writer.
 */
export interface RunEvent {
  run_id: string;
  seq: number;
  ts: string;
  type: RunEventType;
  stage: Stage;
  payload: {
    [k: string]: unknown;
  };
}
